input {

  beats {

    port => 5044
  }
}

filter {

  mutate {

    add_field => {

      "category" => "infrastructure"
    }
  }
}

output {

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "infrastructure-logs-%{+YYYY.MM.dd}"
  }

  stdout {}
}
